
version: 1
raiseExceptions: False

formatters:

    simple:
        format: '[%(module)s] %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

    standard:
        format: '[%(module)s] %(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:

    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    log_file:
        class: reddit_utils.util.MakeFileHandler
        level: DEBUG
        formatter: standard
        filename: logs//everything.log
        encoding: utf8

    danger_log:
        class: reddit_utils.util.MakeFileHandler
        level: ERROR
        formatter: standard
        filename: logs//errors.log
        encoding: utf8

loggers:

    logger:
        level: DEBUG
        handlers: [console, log_file, danger_log]
        propagate: no

root:
    level: DEBUG
    handlers: [console]
